@startuml


createList --|> createTask


class createList{
    + public listName(String topic)
    + public addItem()
    + public removeItem()
    + public editTitle()
    + public displayItems()
    + public displayIncomplete()
    + public displayComplete()
    + public printToFile()
    + public readFromFile()
}

class createTask{
    + public getName()
    + public setName(String name)
    + public editDescription()
    + public isDone()
    + public setDone()
}

@enduml