@startuml

Menu --|> ListMenu
Menu --|> TaskMaker
Menu <|-- MenuMethods
TaskMaker <|-- TaskMethods

class Menu{

    public Text textBox;
    public Button taskButton;
    public TableView<Task> tasksTwo;
    private Stage stage;
    private Scene scene;
    private int viewCount = 0;

    MenuMethods methods = new MenuMethods();

    + public void initialize()
    + public void listMenu(ActionEvent event)
    + public void editTask(ActionEvent event)
    + public void makeTask()
    + public void deleteTask()
    + public void deleteAllTasks()
    + public void importList()
    + public void addToTableView(JSONArray itemList)
    + public void toggleView(ActionEvent event)
    + public void displayAll()
    + public void printToJson()
}

class MenuMethods{

    private int viewCount = 0;

    + public boolean makeTask()
    + public boolean deleteTask(Task task)
    + public boolean deleteAllTasks()
    + public JSONArray importList()
    + public JSONArray parseJson(String file)
    + public boolean addToTableView(JSONArray itemList)
    + public ObservableList<Task> displayComplete()
    + public ObservableList<Task> displayIncomplete()
    + public boolean printToJson()
}

class ListMenu{

    public TextField newListName;
    private Stage stage;
    private Scene scene;

    + public void mainMenu(ActionEvent event)
    + public void createListFromInput(ActionEvent event)
}

class TaskMaker{

    public TextField assignName;
    public TextField assignDescription;
    public DatePicker datePicker;
    public Text completed;
    public Text date;
    public Text description;
    public Text title;
    private Task changeTask;

    TaskMethods methods = new TaskMethods();

    + public void mainMenu(ActionEvent event)
    + public void setupMenu()
    + public void setEditTask(Task task)
    + public void changeTaskName()
    + public void changeTaskDescription()
    + public void changeTaskDate()
    + public void toggleStatus()
}

class TaskMethods{

    private Task changeTask;

    + public Task setEditTask(Task task)
    + public Task changeTaskName(String editName)
    + public Task changeTaskDescription(String editDescription)
    + public Task changeTaskDate(LocalDate date)
    + public Task toggleStatus()
}


@enduml