@startuml

TodoList --|> Task

class TodoList{
    String listTitle
    ObservableList<Task> taskObserve;

    + public void initializeList()
    + public void setTitle(String title)
    + public string getTitle()
}

class Task{
    String taskTitle
    String listName
    String taskDescription
    String dueDate
    Boolean isDone

    + public String getTaskTitle()
    + public void setTaskTitle(String name)
    + public String getListName()
    + public void setListName(String list)
    + public String getTaskDescription()
    + public void setDescription(String descriptionEdit)
    + public String getDueDate()
    + public void setDueDate(String date)
    + public Boolean getIsDone()
    + public void setIsDone(Boolean done)
}

@enduml